// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';

export interface IMetaSeoFields {
  /** Meta Title */
  metaTitle: string;

  /** Meta Description */
  metaDescription?: string | undefined;

  /** Open Graph Image */
  openGraphImage?: Asset | undefined;

  /** Indexable */
  indexable?: boolean | undefined;
}

export interface IMetaSeo extends Entry<IMetaSeoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'metaSeo';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ITemplatePageFields {
  /** Internal Name */
  internalName: string;

  /** Slug */
  slug: string;

  /** SEO */
  seo: IMetaSeo;
}

export interface ITemplatePage extends Entry<ITemplatePageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'templatePage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'metaSeo' | 'templatePage';

export type IEntry = IMetaSeo | ITemplatePage;

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
